create schema if not exists atherystowns;

create table if not exists atherystowns.Nation (
    id bigint generated by default as identity,
    bank binary,
    color varchar(255),
    description varchar(255),
    joinable boolean not null,
    name varchar(255),
    tax double not null,
    version integer not null,
    capital_id bigint,
    leader_id binary,
    primary key (id)
);

create table if not exists atherystowns.Nation_allies (
    nation_id bigint not null,
    ally_nation_id bigint not null,
    primary key (nation_id, ally_nation_id)
);

create table if not exists atherystowns.Nation_enemies (
    nation_id bigint not null,
    enemy_nation_id bigint not null,
    primary key (nation_id, enemy_nation_id)
);

create table if not exists atherystowns.NationPlot (
    id bigint generated by default as identity,
    neCorner varchar(255),
    swCorner varchar(255),
    version integer not null,
    nation_id bigint not null,
    primary key (id)
);

create table if not exists atherystowns.Resident (
    id binary not null,
    lastLogin timestamp,
    lastTownSpawn timestamp,
    name varchar(255),
    registeredOn timestamp,
    title varchar(255),
    version integer not null,
    town_id bigint,
    primary key (id)
);

create table if not exists atherystowns.Resident_friends (
    resident_id binary not null,
    friend_id binary not null,
    primary key (resident_id, friend_id)
);

create table if not exists atherystowns.Resident_nationRoleIds (
    Resident_id binary not null,
    nationRoleIds varchar(255)
);

create table if not exists atherystowns.Resident_townRoleIds (
    Resident_id binary not null,
    townRoleIds varchar(255)
);

create table if not exists atherystowns.Town (
    id bigint generated by default as identity,
    bank binary,
    color varchar(255),
    debt double not null,
    description varchar(255),
    freelyJoinable boolean not null,
    lastRaidCreationDate timestamp,
    lastTaxDate timestamp,
    maxSize integer not null,
    motd varchar(255),
    name varchar(255),
    pvpEnabled boolean not null,
    spawn varchar(255),
    taxFailedCount integer not null,
    taxable boolean not null,
    version integer not null,
    world binary,
    leader_id binary,
    nation_id bigint,
    primary key (id)
);

create table if not exists atherystowns.TownPlot (
    id bigint generated by default as identity,
    neCorner varchar(255),
    swCorner varchar(255),
    version integer not null,
    name varchar(255),
    owner_id binary,
    town_id bigint not null,
    primary key (id)
);

create table if not exists atherystowns.TownPlot_permissions (
    townplot_id bigint not null,
    townplot_permission_id bigint not null,
    primary key (townplot_id, townplot_permission_id)
);

create table if not exists atherystowns.TownPlotPermission (
    id bigint generated by default as identity,
    context varchar(255),
    worldPermission varchar(255),
    primary key (id)
);